# The west manifest file (west.yml) for the nRF Connect SDK (NCS).
#
# The per-workspace west configuration file, ncs/.west/config,
# specifies the location of this manifest file like this:
#
#     [manifest]
#     path = nrf
#
# See the west documentation for more information:
#
# https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/west/index.html

manifest:
  version: "0.10"

  # "remotes" is a list of locations where git repositories are cloned
  # and fetched from.
  remotes:
    # nRF Connect SDK GitHub organization.
    # NCS repositories are hosted here.
    - name: ncs
      url-base: https://github.com/nrfconnect
    # Third-party repository sources:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
    - name: armmbed
      url-base: https://github.com/ARMmbed
    - name: alexa
      url-base: https://github.com/alexa
    - name: nordicsemi
      url-base: https://github.com/NordicSemiconductor
    - name: pelioniot
      url-base: https://github.com/PelionIoT
    - name: memfault
      url-base: https://github.com/memfault
    - name: intellinium-github
      url-base: git@github.com:Intellinium
    - name: intellinium-space-ml
      url-base: git@git.jetbrains.space:intellinium/pod-machine-learning
    - name: intellinium-space-embedded
      url-base: git@git.jetbrains.space:intellinium/embedded

  # If not otherwise specified, the projects below should be obtained
  # from the ncs remote.
  defaults:
    remote: ncs

  group-filter: [-homekit, -nrf-802154, -find-my]

  # "projects" is a list of git repositories which make up the NCS
  # source code.
  projects:

    # The Zephyr RTOS fork in the NCS, along with the subset of its
    # modules which NCS imports directly.
    #
    # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/introduction/index.html
    # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/modules.html
    - name: zephyr
      repo-path: sdk-zephyr
      #revision: 035b805f0cee750d74955f1cd833c7ccf89544da
      #revision: bf50bb052836b673f1e8a4c36cebac55ea53251b
      #revision: c9c7681df3621f9bb5db276cd1edca560366e23b
      revision: 06f11d3d64f8ae42dfa78b1fda3f3629689248ef
      remote: intellinium-github
      import:
        # In addition to the zephyr repository itself, NCS also
        # imports the contents of zephyr/west.yml at the above
        # revision. Only the projects explicitly named in the
        # following allowlist are imported.
        #
        # Note that the zephyr west extensions (like 'build', 'flash',
        # 'debug', etc.) are automatically provided by this import, so
        # there's no need to add a redundant west-commands: key for
        # the zephyr project.
        #
        # Please keep this list sorted alphabetically.
        name-allowlist:
          - TraceRecorderSource
          - canopennode
          - civetweb
          - cmsis
          - edtt
          - fatfs
          - hal_nordic
          - hal_st
          - libmetal
          - littlefs
          - loramac-node
          - lvgl
          - lz4
          - mbedtls
          - mcumgr
          - mipi-sys-t
          - nanopb
          - net-tools
          - nrf_hw_models
          - open-amp
          - openthread
          - segger
          - tensorflow
          - tinycbor
          - tinycrypt

    # NCS repositories.
    #
    # Some of these are also Zephyr modules which have NCS-specific
    # changes.
    - name: mcuboot
      repo-path: sdk-mcuboot
      revision: v1.7.99-ncs4
      path: bootloader/mcuboot
    - name: nrfxlib
      repo-path: sdk-nrfxlib
      path: nrfxlib
      revision: v1.8.0
    - name: trusted-firmware-m
      repo-path: sdk-trusted-firmware-m
      path: modules/tee/tfm
      revision: v1.3.99-ncs3
    - name: tfm-mcuboot # This is used by the trusted-firmware-m module.
      repo-path: sdk-mcuboot
      path: modules/tee/tfm-mcuboot
      revision: v1.7.2
    - name: matter
      repo-path: sdk-connectedhomeip
      path: modules/lib/matter
      revision: v1.8.0
      submodules:
        - name: nlio
          path: third_party/nlio/repo
        - name: nlassert
          path: third_party/nlassert/repo
        - name: pigweed
          path: third_party/pigweed/repo
    - name: nrf-802154
      repo-path: sdk-nrf-802154
      path: nrf-802154
      revision: v1.8.0
      groups:
      - nrf-802154
    - name: cjson
      repo-path: sdk-cjson
      path: modules/lib/cjson
      revision: c6af068b7f05207b28d68880740e4b9ec1e4b50a
    - name: homekit
      repo-path: sdk-homekit
      revision: v1.8.0
      groups:
      - homekit
    - name: find-my
      repo-path: sdk-find-my
      revision: v1.8.0
      groups:
      - find-my
    # Other third-party repositories.
    - name: cmock
      path: test/cmock
      revision: 9d092898ef26ece140d9225e037274b64d4f851e
      remote: throwtheswitch
    - name: unity
      path: test/cmock/vendor/unity
      revision: 74cde089e65c3435ce9aa87d5c69f4f16b7f6ade
      remote: throwtheswitch
    - name: mbedtls-nrf
      path: mbedtls
      repo-path: mbedtls
      revision: mbedtls-2.26.0
      remote: armmbed
    - name: Alexa-Gadgets-Embedded-Sample-Code
      path: modules/alexa-embedded
      revision: face92d8c62184832793f518bb1f19379538c5c1
      remote: alexa
    - name: mbed-cloud-client
      path: modules/lib/pelion-dm
      revision: 4.10.0
      remote: pelioniot
    - name: cddl-gen
      remote: nordicsemi
      revision: 24f1b2b0c64c694b7f9ac1b7eab60b39236ca0bf
      path: modules/lib/cddl-gen
    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      revision: 0.27.3
      remote: memfault
    - name: hal_intellinium
      remote: intellinium-github
      revision: 4ceb71221b5c99d609fa72ad41622c5c65082ed4
      path: modules/hal/intellinium
    - name: embedded-itl-lib
      remote: intellinium-github
      revision: 92f6441a6bfa5c64670f4714b114138ba4e19a32
      path: modules/itl-lib
    - name: ml-ppg-algorithm
      remote: intellinium-github
      revision: 49f09069eb8fa66de0d1d9b7cd1f38b9d4fee441
      path: modules/itl-ml/ppg
    - name: ml-ppg-cognitive-test
      remote: intellinium-github
      revision: 7ca9059aa507dc7b57bad150c8fc101d935968f1
      path: modules/itl-ml/ppg_ct


  # West-related configuration for the nrf repository.
  self:
    # This repository should be cloned to ncs/nrf.
    path: nrf
    # This line configures west extensions which are currently only
    # for internal use by NCS maintainers.
    west-commands: scripts/west-commands.yml
